### ISSUE TITLE
ReadAll from ConPTY

### ISSUE THREAD

**Issue by zhiburt** [ActiveState/termtest#5]
Hey there,

I am curious if it's possible to ReadAll content from spawned process.

Essentially read doesn't get a error when the process is gone which is does with general Pipes.

To reproduce:

```go
package main

import (
	"fmt"

	"github.com/ActiveState/termtest/conpty"
)

func main() {
	pty, err := conpty.New(40, 40)
	if err != nil {
		panic(err)
	}

	_, _, err = pty.Spawn("C:\\Windows\\system32\\PING.EXE", nil, nil)
	if err != nil {
		panic(err)
	}

	out := pty.OutPipe()
	for {
		buf := make([]byte, 30)
		n, err := out.Read(buf)
		if err != nil {
			panic(err)
		}

		fmt.Println(buf[:n])
	}
}
```

PS: I was investigating this issue for a while and hasn't found any way...

**Comment by zhiburt** [comment]
ref: https://github.com/microsoft/terminal/issues/4564

**Comment by mdrohmann** [comment]
As mentioned in the issue that you linked, there is no EOF file signal for when the process goes away.

You could however, return the `pid` that is returned by `pty.Spawn` and make into a process via [`os.FindProcess`](https://pkg.go.dev/os#FindProcess), and that returned process you can wait on.  That way you know when you have to stop reading.

We'll not implementing a function for that in conpty though.  So, I am closing this issue.
